import cssIcon from "../../assets/icons/icons8-css-64.png";
import jsIcon from "../../assets/icons/icons8-java-script-64.png";
import htmlIcon from "../../assets/icons/icons8-html-64.png";
import aiIcon from "../../assets/icons/icons8-adobe-illustrator.svg";
import reactIcon from "../../assets/icons/icons8-react.svg";

export const skillsArr = [
  { category: "Web Development & Design",
    mainImg: "",
    skills: [ { skillImg: jsIcon,
                skillName: "Javascript",
                level: 3,
              },
              { skillImg: cssIcon,
                skillName: "CSS",
                level: 2,
              },
              { skillImg: htmlIcon,
                skillName: "HTML",
                startDate: 2,
              },
              { skillImg: aiIcon,
                skillName: "Illustrator",
                startDate: 1,
              },
              { skillImg: reactIcon,
                skillName: "ReactJS",
                startDate: 2,
              },
    ]
              
  },
  { skillCategory: "Design",
    mainImg: "",
    skills: [ { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
            ]
  },
  { skillCategory: "Development",
    mainImg: "",
    skills: [ { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
            ]
  },
  { skillCategory: "Soft Skills",
    mainImg: "",
    skills: [ { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
            ]
  },
]