import cssIcon from "../../assets/icons/css_icon.svg";
import jsIcon from "../../assets/icons/js_icon.svg";
import htmlIcon from "../../assets/icons/html_icon.svg";
import aiIcon from "../../assets/icons/ai_icon.svg";
import reactIcon from "../../assets/icons/react_icon.png";

export const skillsArr = [
  { category: "Web Development & Design",
    mainImg: "",
    skills: [ { image: jsIcon,
                name: "Javascript",
                area: "row1",
              },
              { image: cssIcon,
                name: "CSS",
                area: "row1",
              },
              { image: htmlIcon,
                name: "HTML",
                area: "row1",
              },
              { image: aiIcon,
                name: "Illustrator",
                area: "row2",
              },
              { image: reactIcon,
                name: "React",
                area: "row2",
              },
    ]
              
  },
  { skillCategory: "Life",
    mainImg: "",
    skills: [ { skillImg: "",
                skillName: "Self-Management",
                startDate: "",
              },
              { skillImg: "",
                skillName: "Decision Making",
                startDate: "",
              },
              { skillImg: "",
                skillName: "Problem-Solving",
                startDate: "",
              },
              { skillImg: "",
                skillName: "Learning Agility",
                startDate: "",
              },
            ]
  },
  { skillCategory: "Development",
    mainImg: "",
    skills: [ { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
            ]
  },
  { skillCategory: "Soft Skills",
    mainImg: "",
    skills: [ { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
              { skillImg: "",
                skillName: "",
                startDate: "",
              },
            ]
  },
]